-- BBLeague: modelo inicial de competiciones en Supabase
-- Ejecutar en el SQL Editor de Supabase.

create extension if not exists pgcrypto;

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table public.races (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.tournaments (
  id bigint generated by default as identity primary key,
  name text not null,
  year integer not null check (year between 2000 and 2100),
  unique (name, year)
);

create table public.tournament_users (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  race_id bigint not null references public.races(id),
  registered_at timestamptz not null default now(),
  unique (tournament_id, user_id),
  unique (id, tournament_id)
);

create table public.rounds (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  number integer not null check (number > 0),
  start_date date,
  end_date date,
  status text not null default 'pending'
    check (status in ('pending', 'active', 'closed')),
  unique (tournament_id, number),
  unique (id, tournament_id),
  check (end_date is null or start_date is null or end_date >= start_date)
);

create table public.matches (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  round_id bigint not null,
  tournament_user_a_id bigint not null,
  tournament_user_b_id bigint not null,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'played', 'cancelled')),
  created_at timestamptz not null default now(),
  foreign key (round_id, tournament_id)
    references public.rounds(id, tournament_id) on delete cascade,
  foreign key (tournament_user_a_id, tournament_id)
    references public.tournament_users(id, tournament_id),
  foreign key (tournament_user_b_id, tournament_id)
    references public.tournament_users(id, tournament_id),
  check (tournament_user_a_id <> tournament_user_b_id),
  unique (round_id, tournament_user_a_id),
  unique (round_id, tournament_user_b_id)
);

create table public.results (
  id bigint generated by default as identity primary key,
  match_id bigint not null unique references public.matches(id) on delete cascade,
  submitted_by uuid not null references public.users(id),
  touchdowns_a integer not null default 0 check (touchdowns_a >= 0),
  touchdowns_b integer not null default 0 check (touchdowns_b >= 0),
  casualties_a integer not null default 0 check (casualties_a >= 0),
  casualties_b integer not null default 0 check (casualties_b >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'disputed')),
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index tournament_users_tournament_idx
  on public.tournament_users (tournament_id);
create index matches_round_idx on public.matches (round_id);
create index results_status_idx on public.results (status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger results_set_updated_at
before update on public.results
for each row execute function public.set_updated_at();

-- Crea el perfil público al registrarse un usuario en Supabase Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, username, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    new.email
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Permite iniciar sesión con username aunque Supabase Auth use email internamente.
create or replace function public.get_auth_email(login_username text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select email
  from public.users
  where username = login_username;
$$;

grant execute on function public.get_auth_email(text) to anon, authenticated;

-- Clasificación individual calculada a partir de resultados confirmados.
create or replace view public.classification as
with participant_stats as (
  select
    tp.tournament_id,
    tp.id as tournament_user_id,
    u.id as user_id,
    u.username,
    race.name as race_name,
    count(result.id)::integer as played,
    count(result.id) filter (
      where (m.tournament_user_a_id = tp.id and result.touchdowns_a > result.touchdowns_b)
        or (m.tournament_user_b_id = tp.id and result.touchdowns_b > result.touchdowns_a)
    )::integer as wins,
    count(result.id) filter (
      where result.touchdowns_a = result.touchdowns_b
    )::integer as draws,
    count(result.id) filter (
      where (m.tournament_user_a_id = tp.id and result.touchdowns_a < result.touchdowns_b)
        or (m.tournament_user_b_id = tp.id and result.touchdowns_b < result.touchdowns_a)
    )::integer as losses,
    coalesce(sum(
      case when m.tournament_user_a_id = tp.id then result.touchdowns_a else result.touchdowns_b end
    ), 0)::integer as touchdowns_for,
    coalesce(sum(
      case when m.tournament_user_a_id = tp.id then result.touchdowns_b else result.touchdowns_a end
    ), 0)::integer as touchdowns_against,
    coalesce(sum(
      case when m.tournament_user_a_id = tp.id then result.casualties_a else result.casualties_b end
    ), 0)::integer as casualties_for,
    coalesce(sum(
      case when m.tournament_user_a_id = tp.id then result.casualties_b else result.casualties_a end
    ), 0)::integer as casualties_against,
    coalesce(sum(
      case
        when m.tournament_user_a_id = tp.id and result.touchdowns_a > result.touchdowns_b then 3
        when m.tournament_user_b_id = tp.id and result.touchdowns_b > result.touchdowns_a then 3
        when result.touchdowns_a = result.touchdowns_b then 1
        else 0
      end
    ), 0)::integer as points
  from public.tournament_users tp
  join public.users u on u.id = tp.user_id
  join public.races race on race.id = tp.race_id
  left join public.matches m
    on m.tournament_id = tp.tournament_id
  and (m.tournament_user_a_id = tp.id or m.tournament_user_b_id = tp.id)
  left join public.results result
    on result.match_id = m.id and result.status = 'confirmed'
  group by tp.tournament_id, tp.id, u.id, u.username, race.name
)
select
  row_number() over (
    partition by tournament_id
    order by points desc,
             (touchdowns_for - touchdowns_against) desc,
             touchdowns_for desc,
             casualties_for desc,
             username
  )::integer as rank,
  participant_stats.*,
  (touchdowns_for - touchdowns_against)::integer as touchdown_difference,
  (casualties_for - casualties_against)::integer as casualty_difference
from participant_stats;

alter table public.users enable row level security;
alter table public.races enable row level security;
alter table public.tournaments enable row level security;
alter table public.tournament_users enable row level security;
alter table public.rounds enable row level security;
alter table public.matches enable row level security;
alter table public.results enable row level security;

create policy "public can read users"
  on public.users for select using (true);

create policy "public can read active races"
  on public.races for select using (active = true);

create policy "public can read tournaments"
  on public.tournaments for select using (true);

create policy "authenticated users can create tournaments"
  on public.tournaments for insert
  with check (auth.uid() is not null);

create policy "public can read tournament users"
  on public.tournament_users for select using (true);
create policy "users can register themselves"
  on public.tournament_users for insert
  with check (user_id = auth.uid());
create policy "users can update their registration"
  on public.tournament_users for update
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
create policy "users can delete their registration"
  on public.tournament_users for delete using (user_id = auth.uid());

create policy "public can read rounds"
  on public.rounds for select using (true);

create policy "public can read matches"
  on public.matches for select using (true);

create policy "public can read results"
  on public.results for select using (true);
create policy "participants can submit results"
  on public.results for insert
  with check (
    submitted_by = auth.uid()
    and exists (
      select 1
      from public.matches m
      join public.tournament_users tpa on tpa.id = m.tournament_user_a_id
      join public.tournament_users tpb on tpb.id = m.tournament_user_b_id
      where m.id = match_id
        and (tpa.user_id = auth.uid() or tpb.user_id = auth.uid())
    )
  );
create policy "submitters can update results"
  on public.results for update
  using (submitted_by = auth.uid())
  with check (submitted_by = auth.uid());
