-- Storage privado para rosters.
-- Cada roster pertenece a una unica inscripcion en un torneo.

begin;

create table public.rosters (
  id bigint generated by default as identity primary key,
  tournament_user_id bigint not null unique
    references public.tournament_users(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  mime_type text not null default 'application/pdf'
    check (mime_type = 'application/pdf'),
  uploaded_at timestamptz not null default now()
);

create index rosters_tournament_user_idx
  on public.rosters (tournament_user_id);

alter table public.rosters enable row level security;

create policy "users can read their roster"
  on public.rosters for select
  to authenticated
  using (
    exists (
      select 1
      from public.tournament_users tu
      where tu.id = tournament_user_id
        and tu.user_id = auth.uid()
    )
  );

create policy "users can upload their roster"
  on public.rosters for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.tournament_users tu
      where tu.id = tournament_user_id
        and tu.user_id = auth.uid()
    )
  );

create policy "users can update their roster"
  on public.rosters for update
  to authenticated
  using (
    exists (
      select 1
      from public.tournament_users tu
      where tu.id = tournament_user_id
        and tu.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.tournament_users tu
      where tu.id = tournament_user_id
        and tu.user_id = auth.uid()
    )
  );

insert into storage.buckets (id, name, public)
values ('rosters', 'rosters', false)
on conflict (id) do update set public = false;

create policy "users can upload own roster files"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'rosters'
    and exists (
      select 1
      from public.tournament_users tu
      where tu.id = split_part(name, '/', 1)::bigint
        and tu.user_id = auth.uid()
    )
  );

create policy "users can read own roster files"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'rosters'
    and exists (
      select 1
      from public.tournament_users tu
      where tu.id = split_part(name, '/', 1)::bigint
        and tu.user_id = auth.uid()
    )
  );

create policy "users can update own roster files"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'rosters'
    and exists (
      select 1
      from public.tournament_users tu
      where tu.id = split_part(name, '/', 1)::bigint
        and tu.user_id = auth.uid()
    )
  )
  with check (
    bucket_id = 'rosters'
    and exists (
      select 1
      from public.tournament_users tu
      where tu.id = split_part(name, '/', 1)::bigint
        and tu.user_id = auth.uid()
    )
  );

commit;
