-- Bases PDF de los torneos.
-- Una unica base por torneo, accesible a sus participantes.

begin;

create table public.tournament_bases (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null unique references public.tournaments(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  mime_type text not null default 'application/pdf'
    check (mime_type = 'application/pdf'),
  uploaded_at timestamptz not null default now()
);

alter table public.tournament_bases enable row level security;

create policy "participants can read tournament bases"
  on public.tournament_bases for select
  to authenticated
  using (
    exists (
      select 1
      from public.tournament_users
      where tournament_users.tournament_id = tournament_bases.tournament_id
        and tournament_users.user_id = auth.uid()
    )
  );

create policy "creators can manage tournament bases"
  on public.tournament_bases for all
  to authenticated
  using (
    exists (
      select 1
      from public.tournaments
      where public.tournaments.id = tournament_bases.tournament_id
        and public.tournaments.creator_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.tournaments
      where public.tournaments.id = tournament_id
        and public.tournaments.creator_id = auth.uid()
    )
  );

insert into storage.buckets (id, name, public)
values ('tournament-documents', 'tournament-documents', false)
on conflict (id) do update set public = false;

create policy "creators can upload tournament bases"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'tournament-documents'
    and exists (
      select 1
      from public.tournaments
      where public.tournaments.id = split_part(name, '/', 1)::bigint
        and public.tournaments.creator_id = auth.uid()
    )
  );

create policy "participants can read tournament bases files"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'tournament-documents'
    and exists (
      select 1
      from public.tournament_users
      where public.tournament_users.tournament_id = split_part(name, '/', 1)::bigint
        and public.tournament_users.user_id = auth.uid()
    )
  );

create policy "creators can update tournament bases files"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'tournament-documents'
    and exists (
      select 1
      from public.tournaments
      where public.tournaments.id = split_part(name, '/', 1)::bigint
        and public.tournaments.creator_id = auth.uid()
    )
  )
  with check (
    bucket_id = 'tournament-documents'
    and exists (
      select 1
      from public.tournaments
      where public.tournaments.id = split_part(name, '/', 1)::bigint
        and public.tournaments.creator_id = auth.uid()
    )
  );

commit;
